### ISSUE TITLE
Download specific file version?

### ISSUE THREAD

**Issue by timriffe** [eshom/covid-age-data#1]
Excellent package idea, thanks! Do you think you can add an argument to download a particular file by version number or date approximation? This would make the package helpful for reproducibility and things like that.  For example, for the `inputDB`, here's the OSF version table: [https://osf.io/9dsfk/?show=revision](https://osf.io/9dsfk/?show=revision)

**Comment by eshom** [comment]
Thanks. I'll implement it soon. I'm not sure the `osfr` package has a field for downloading specific revisions. Worst case, I'll directly make the appropriate API requests.

**Comment by eshom** [comment]
Added the requested function (88aec95). Thanks again. For now this feature lives in a separate function, which uses `utils::download.file()` to get the files. I'll make one main downloading function if the `osfr` package adds a feature to download specific versions. Or I might drop using `osfr` entirely. We'll see.
