### ISSUE TITLE
download_covid issue: "Error: The requested file (43ucn) could not be found in node `mpwjq` "

### ISSUE THREAD

**Issue by yildizyasin** [eshom/covid-age-data#5]
When I try to run the following code block, it gives the error: 

_**Error: The requested file (43ucn) could not be found in node `mpwjq`**_

I tried to delete and reinstall the package. It seems like the file locations are changed. How can I easily fix this issue?

`> df <- download_covid(data = "Output_10")
Downloading Output_10.zip
  |========================================================================================================================================| 100%
Error: The requested file (43ucn) could not be found in node `mpwjq`
Run `rlang::last_error()` to see where the error occurred.

**Comment by eshom** [comment]
Hi @yildizyasin , thanks for letting me know!

Looks like the problem is with the `osfr` backend. So I'll raise it to them.

For now, you can use `download_covid_version()`, which doesn't use `osfr`, and choose the latest version (394 at the time of writing this).

```r
df <- download_covid_version(data = "Output_10", version = 394)
```
