### ISSUE TITLE
download error and suggested fix

### ISSUE THREAD

**Issue by timriffe** [eshom/covid-age-data#8]
The following code currently fails:

```
library(covidAgeData)
download_covid("inputDB",download_only = TRUE)
```
The error is `The requested file (9dsfk) could not be found in node mpwjq `. I didn't check, but possibly it's just now necessary to specify that the file is inside the `Data` folder. However, the following `osfr` code works to identify and download the file:

```
library(osfr)
osf_ls_files(cr_project, path = "Data") %>% 
  filter(name == "inputDB.zip") %>% 
  osf_download(conflicts = "overwrite")
```

So, I think the fix will probably be an easy one. Do you have time to take a look @eshom or should I take a stab and make a PR?

**Comment by eshom** [comment]
Hi Tim,
Already ahead of you! This was fixed in #5, so try reinstalling the package.

However if you have some spare time, timriffe/covid_age/issues/143 would be helpful, so I can fix `qualityMetrics` and add `offset.csv`

Thanks for reporting!
